# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 7 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been open 60 days with no activity"
          stale-pr-message: "This PR is open for 45 days with no activity"
          stale-issue-label: "no activity"
          stale-pr-label: "no activity"
          labels-to-remove-when-unstale: "no activity"
          days-before-issue-stale: 60
          days-before-pr-stale: 30
          exempt-all-milestones: true
          days-before-close: -1
