# Build and Test - make sure code has no issues
#

name: Test Execution Plan

# list of trigger events https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  # regardless of branch, run this default workflow to verify code
  workflow_dispatch:
    inputs:
      milestone-version:
        required: true
        type: string
        description: milestone version to release prod. e.g. 0.1.2
      execution-type:
        required: true
        type: choice
        description: What type of test execution is this for
        options:
          - regression
          - feature

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  message:
    name: Display Warning
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a default workflow. Please run on valid milestone branch"
