# Prepare UI artifact to deploy as statis site

name: UI Artifact Build & Deploy

# list of trigger events https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
    workflow_run:
      workflows: ["UI Build"]
      types: [completed]
      branches:
        - master
    workflow_dispatch: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_artifact:
    name: create artifact
    runs-on: ubuntu-latest
    environment: static-site
    outputs:
      artifact_id: ${{ steps.upload-artifact-step.outputs.artifact-id }}
      artifact_url: ${{ steps.upload-artifact-step.outputs.artifact-url }}
      artifact_digest: ${{ steps.upload-artifact-step.outputs.artifact-digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm ci
      - run: cp src/demo/dummy.ts src/demo/index.ts
      - run: npm run build
      - name: upload artifact
        id: upload-artifact-step
        uses: actions/upload-artifact@v4
        with:
          name: personal-finance-ui-static
          path: ./build/
          if-no-files-found: error
          retention-days: 2
          overwrite: true
      - name: artifact Outputs
        run: |
          echo Artifact ID is ${{ steps.upload-artifact-step.outputs.artifact-id }}
          echo Artifact URL is ${{ steps.upload-artifact-step.outputs.artifact-url }}
          echo Artifact DIGEST is ${{ steps.upload-artifact-step.outputs.artifact-digest }}
    
  deployment:
    name: deploy static UI
    runs-on: ubuntu-latest
    needs: build_artifact
    environment: static-site
    permissions: 
      contents: write
      id-token: write
    steps:
      - name: trigger another workflow deploy static site in AWS
        run: |
          curl -L --fail \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\":false,\"integration\":true, \"artifact_id\": \"$artifact_id\", \"artifact_url\": \"$artifact_url\", \"repo_run_id\": \"$grun_id\", \"ui_repository\": \"$ui_repository\"}}"
        env:
            repo_name: ${{ vars.UI_DEPLOY_REPO_NAME }}
            repo_owner: ${{ github.repository_owner }}
            event_type: ${{ vars.UI_DEPLOY_EVENT_TYPE }}
            artifact_id: ${{ needs.build_artifact.outputs.artifact_id }}
            artifact_url: ${{ needs.build_artifact.outputs.artifact_url }}
            grun_id: ${{ github.run_id }}
            ui_repository: ${{ github.repository }}
