# Deploy UI for demo

name: Deploy Demo UI

# list of trigger events https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  workflow_run:
    workflows: ["UI Build"]
    types: [completed]
    branches:
      - master
  # manual trigger allowed only for milestone branches
  workflow_dispatch:
    
# only 1 workflow can be allowed for repository. 
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pages: write
  contents: write
  deployments: write

jobs:
  # test_echo:
  #   name: print context values
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo github context json values = $GITHUB_CONTEXT_JSON
  #         echo vars context json = $VARS_JSON
  #       env:
  #         GITHUB_CONTEXT_JSON: ${{ toJSON(github) }}
  #         VARS_JSON: ${{ toJSON(vars) }}
  validate_run:
    name: Validating Run condition
    runs-on: ubuntu-latest
    outputs:
      wfdispatch_eligible: ${{ steps.wf_dispatch.outputs.milestone_dispatch_run }}
      wfrun_eligible: ${{ steps.wf_run.outputs.master_run }}
      wfdispatchrun_eligible: ${{ steps.wf_dispatch_run.outputs.deploy_run }}
      wfdispatchrun2_eligible: ${{ steps.wf_dispatch_run2.outputs.deploy_run2 }}
    steps:
      - run: |
          echo milestone_dispatch_run=true
          echo milestone_dispatch_run=true >> $GITHUB_OUTPUT
        id: wf_dispatch
        if: github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')
      - run: |
          echo master_run=true
          echo master_run=true >> $GITHUB_OUTPUT
        id: wf_run
        if: github.event_name == 'workflow_run' && github.ref=='refs/heads/master'
      - run: |
          echo deploy_run=true
          echo deploy_run=true >> $GITHUB_OUTPUT
        id: wf_dispatch_run
        if: (github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')) || (github.event_name == 'workflow_run' && github.ref=='refs/heads/master')
      - run: |
          echo MILESTONE_RUN=$MILESTONE_RUN
          echo MASTER_RUN=$MASTER_RUN
          if [ "$MILESTONE_RUN" = true ] || [ "$MASTER_RUN" = true ]; then
            echo deploy_run2=true
            echo deploy_run2=true >> $GITHUB_OUTPUT
          else
            echo deploy_run2=false
            echo deploy_run2=false >> $GITHUB_OUTPUT
          fi
        id: wf_dispatch_run2
        env:
          MILESTONE_RUN: ${{ steps.wf_dispatch.outputs.milestone_dispatch_run }}
          MASTER_RUN: ${{ steps.wf_run.outputs.master_run }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: 
      - validate_run
    # if: github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')
    if: ${{ needs.validate_run.outputs.wfdispatch_eligible == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm --version
      - run: npm ci
      - run: npm run build

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm --version
      - run: npm ci
      - run: npm run test --coverage

  deploy_demo:
    name: gh page build
    runs-on: ubuntu-latest
    needs: 
      - unittest
      - validate_run
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
    environment: github-pages
    # if: (github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')) || (github.event_name == 'workflow_run' && github.ref=='refs/heads/master')
    if: ${{ always() && needs.validate_run.outputs.wfdispatchrun_eligible == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm --version
      - run: npm ci
      - run: cp src/demo/demo.ts src/demo/index.ts
      - run: npm run build
        env:
          REACT_APP_BASE_PATH: ${{ vars.GH_REACT_APP_BASE_PATH }}
          REACT_APP_REST_API_BASE_PATH: ${{ vars.GH_REACT_APP_REST_API_BASE_PATH }}
          REACT_APP_MINIMUM_SESSION_TIME: ${{ vars.GH_REACT_APP_MINIMUM_SESSION_TIME }}
          GENERATE_SOURCEMAP: ${{ vars.GH_GENERATE_SOURCEMAP }}
          PUBLIC_URL: ${{ vars.GH_PUBLIC_URL }}
      # - run: gh-pages -d build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
